git:
	git add .
	git commit -m "auto"
	git push

main:
	g++ -std=c++11 main.cpp -o main.out
	./main.out test.wav



reader:
	g++ -std=c++11 WaveReader.cpp -o WaveReader.out
	./WaveReader.out part_output.wav